'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property NumOfExtruders() As String
            Get
                Return CType(Me("NumOfExtruders"),String)
            End Get
            Set
                Me("NumOfExtruders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property Lev_LFx() As String
            Get
                Return CType(Me("Lev_LFx"),String)
            End Get
            Set
                Me("Lev_LFx") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property Lev_LFy() As String
            Get
                Return CType(Me("Lev_LFy"),String)
            End Get
            Set
                Me("Lev_LFy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Lev_LFz() As String
            Get
                Return CType(Me("Lev_LFz"),String)
            End Get
            Set
                Me("Lev_LFz") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property Lev_LRx() As String
            Get
                Return CType(Me("Lev_LRx"),String)
            End Get
            Set
                Me("Lev_LRx") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property Lev_LRy() As String
            Get
                Return CType(Me("Lev_LRy"),String)
            End Get
            Set
                Me("Lev_LRy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Lev_LRz() As String
            Get
                Return CType(Me("Lev_LRz"),String)
            End Get
            Set
                Me("Lev_LRz") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property Lev_RFx() As String
            Get
                Return CType(Me("Lev_RFx"),String)
            End Get
            Set
                Me("Lev_RFx") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property Lev_RFy() As String
            Get
                Return CType(Me("Lev_RFy"),String)
            End Get
            Set
                Me("Lev_RFy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Lev_RFz() As String
            Get
                Return CType(Me("Lev_RFz"),String)
            End Get
            Set
                Me("Lev_RFz") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property Lev_RRx() As String
            Get
                Return CType(Me("Lev_RRx"),String)
            End Get
            Set
                Me("Lev_RRx") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property Lev_RRy() As String
            Get
                Return CType(Me("Lev_RRy"),String)
            End Get
            Set
                Me("Lev_RRy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Lev_RRz() As String
            Get
                Return CType(Me("Lev_RRz"),String)
            End Get
            Set
                Me("Lev_RRz") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property Lev_MIDx() As String
            Get
                Return CType(Me("Lev_MIDx"),String)
            End Get
            Set
                Me("Lev_MIDx") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property Lev_MIDy() As String
            Get
                Return CType(Me("Lev_MIDy"),String)
            End Get
            Set
                Me("Lev_MIDy") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Lev_MIDz() As String
            Get
                Return CType(Me("Lev_MIDz"),String)
            End Get
            Set
                Me("Lev_MIDz") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property PrePr_x() As String
            Get
                Return CType(Me("PrePr_x"),String)
            End Get
            Set
                Me("PrePr_x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property PrePr_z() As String
            Get
                Return CType(Me("PrePr_z"),String)
            End Get
            Set
                Me("PrePr_z") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property ChngNoz_x() As String
            Get
                Return CType(Me("ChngNoz_x"),String)
            End Get
            Set
                Me("ChngNoz_x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property ChngNoz_y() As String
            Get
                Return CType(Me("ChngNoz_y"),String)
            End Get
            Set
                Me("ChngNoz_y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property Cali_E_x() As String
            Get
                Return CType(Me("Cali_E_x"),String)
            End Get
            Set
                Me("Cali_E_x") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property Cali_E_y() As String
            Get
                Return CType(Me("Cali_E_y"),String)
            End Get
            Set
                Me("Cali_E_y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("150")>  _
        Public Property Cali_E_z() As String
            Get
                Return CType(Me("Cali_E_z"),String)
            End Get
            Set
                Me("Cali_E_z") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("115200")>  _
        Public Property PortBaud() As String
            Get
                Return CType(Me("PortBaud"),String)
            End Get
            Set
                Me("PortBaud") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property PortBytes() As String
            Get
                Return CType(Me("PortBytes"),String)
            End Get
            Set
                Me("PortBytes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("N")>  _
        Public Property PortParity() As String
            Get
                Return CType(Me("PortParity"),String)
            End Get
            Set
                Me("PortParity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PortStopBits() As String
            Get
                Return CType(Me("PortStopBits"),String)
            End Get
            Set
                Me("PortStopBits") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property DefaultPort() As String
            Get
                Return CType(Me("DefaultPort"),String)
            End Get
            Set
                Me("DefaultPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property MaxPorts() As String
            Get
                Return CType(Me("MaxPorts"),String)
            End Get
            Set
                Me("MaxPorts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PLA")>  _
        Public Property Matl1_Name() As String
            Get
                Return CType(Me("Matl1_Name"),String)
            End Get
            Set
                Me("Matl1_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("210")>  _
        Public Property Matl1_Hot() As String
            Get
                Return CType(Me("Matl1_Hot"),String)
            End Get
            Set
                Me("Matl1_Hot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property Matl1_Bed() As String
            Get
                Return CType(Me("Matl1_Bed"),String)
            End Get
            Set
                Me("Matl1_Bed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property Matl1_Fan() As String
            Get
                Return CType(Me("Matl1_Fan"),String)
            End Get
            Set
                Me("Matl1_Fan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("PETG")>  _
        Public Property Matl2_Name() As String
            Get
                Return CType(Me("Matl2_Name"),String)
            End Get
            Set
                Me("Matl2_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("245")>  _
        Public Property Matl2_Hot() As String
            Get
                Return CType(Me("Matl2_Hot"),String)
            End Get
            Set
                Me("Matl2_Hot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("70")>  _
        Public Property Matl2_Bed() As String
            Get
                Return CType(Me("Matl2_Bed"),String)
            End Get
            Set
                Me("Matl2_Bed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Matl2_Fan() As String
            Get
                Return CType(Me("Matl2_Fan"),String)
            End Get
            Set
                Me("Matl2_Fan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ABS")>  _
        Public Property Matl3_Name() As String
            Get
                Return CType(Me("Matl3_Name"),String)
            End Get
            Set
                Me("Matl3_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("245")>  _
        Public Property Matl3_Hot() As String
            Get
                Return CType(Me("Matl3_Hot"),String)
            End Get
            Set
                Me("Matl3_Hot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("105")>  _
        Public Property Matl3_Bed() As String
            Get
                Return CType(Me("Matl3_Bed"),String)
            End Get
            Set
                Me("Matl3_Bed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Matl3_Fan() As String
            Get
                Return CType(Me("Matl3_Fan"),String)
            End Get
            Set
                Me("Matl3_Fan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Other")>  _
        Public Property Matl4_Name() As String
            Get
                Return CType(Me("Matl4_Name"),String)
            End Get
            Set
                Me("Matl4_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Matl4_Hot() As String
            Get
                Return CType(Me("Matl4_Hot"),String)
            End Get
            Set
                Me("Matl4_Hot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Matl4_Bed() As String
            Get
                Return CType(Me("Matl4_Bed"),String)
            End Get
            Set
                Me("Matl4_Bed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Matl4_Fan() As String
            Get
                Return CType(Me("Matl4_Fan"),String)
            End Get
            Set
                Me("Matl4_Fan") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Heated_Bed() As Boolean
            Get
                Return CType(Me("Heated_Bed"),Boolean)
            End Get
            Set
                Me("Heated_Bed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property Retraction() As String
            Get
                Return CType(Me("Retraction"),String)
            End Get
            Set
                Me("Retraction") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property ExtrudeAmt() As String
            Get
                Return CType(Me("ExtrudeAmt"),String)
            End Get
            Set
                Me("ExtrudeAmt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property PrimeAmt() As String
            Get
                Return CType(Me("PrimeAmt"),String)
            End Get
            Set
                Me("PrimeAmt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoLevel() As Boolean
            Get
                Return CType(Me("AutoLevel"),Boolean)
            End Get
            Set
                Me("AutoLevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("200")>  _
        Public Property ChngNoz_z() As String
            Get
                Return CType(Me("ChngNoz_z"),String)
            End Get
            Set
                Me("ChngNoz_z") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property Bed_Xmax() As String
            Get
                Return CType(Me("Bed_Xmax"),String)
            End Get
            Set
                Me("Bed_Xmax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property Bed_Ymax() As String
            Get
                Return CType(Me("Bed_Ymax"),String)
            End Get
            Set
                Me("Bed_Ymax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00")>  _
        Public Property HomeOffsetZ() As String
            Get
                Return CType(Me("HomeOffsetZ"),String)
            End Get
            Set
                Me("HomeOffsetZ") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00")>  _
        Public Property HomeOffsetX() As String
            Get
                Return CType(Me("HomeOffsetX"),String)
            End Get
            Set
                Me("HomeOffsetX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00")>  _
        Public Property HomeOffsetY() As String
            Get
                Return CType(Me("HomeOffsetY"),String)
            End Get
            Set
                Me("HomeOffsetY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom1() As String
            Get
                Return CType(Me("Custom1"),String)
            End Get
            Set
                Me("Custom1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom2() As String
            Get
                Return CType(Me("Custom2"),String)
            End Get
            Set
                Me("Custom2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom3() As String
            Get
                Return CType(Me("Custom3"),String)
            End Get
            Set
                Me("Custom3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Custom4() As String
            Get
                Return CType(Me("Custom4"),String)
            End Get
            Set
                Me("Custom4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Script1() As String
            Get
                Return CType(Me("Script1"),String)
            End Get
            Set
                Me("Script1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Script2() As String
            Get
                Return CType(Me("Script2"),String)
            End Get
            Set
                Me("Script2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Script3() As String
            Get
                Return CType(Me("Script3"),String)
            End Get
            Set
                Me("Script3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Script4() As String
            Get
                Return CType(Me("Script4"),String)
            End Get
            Set
                Me("Script4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoPortOpen() As Boolean
            Get
                Return CType(Me("AutoPortOpen"),Boolean)
            End Get
            Set
                Me("AutoPortOpen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultXAccel() As String
            Get
                Return CType(Me("DefaultXAccel"),String)
            End Get
            Set
                Me("DefaultXAccel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultYAccel() As String
            Get
                Return CType(Me("DefaultYAccel"),String)
            End Get
            Set
                Me("DefaultYAccel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultXJerk() As String
            Get
                Return CType(Me("DefaultXJerk"),String)
            End Get
            Set
                Me("DefaultXJerk") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DefaultYJerk() As String
            Get
                Return CType(Me("DefaultYJerk"),String)
            End Get
            Set
                Me("DefaultYJerk") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property PrePr_y() As String
            Get
                Return CType(Me("PrePr_y"),String)
            End Get
            Set
                Me("PrePr_y") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Standard")>  _
        Public Property WhatColor() As String
            Get
                Return CType(Me("WhatColor"),String)
            End Get
            Set
                Me("WhatColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property JunctionDeviation() As String
            Get
                Return CType(Me("JunctionDeviation"),String)
            End Get
            Set
                Me("JunctionDeviation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("500")>  _
        Public Property DefaultPAccel() As String
            Get
                Return CType(Me("DefaultPAccel"),String)
            End Get
            Set
                Me("DefaultPAccel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("750")>  _
        Public Property DefaultTAccel() As String
            Get
                Return CType(Me("DefaultTAccel"),String)
            End Get
            Set
                Me("DefaultTAccel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PreHeatSync() As Boolean
            Get
                Return CType(Me("PreHeatSync"),Boolean)
            End Get
            Set
                Me("PreHeatSync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR1Profile() As String
            Get
                Return CType(Me("PR1Profile"),String)
            End Get
            Set
                Me("PR1Profile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR1Port() As String
            Get
                Return CType(Me("PR1Port"),String)
            End Get
            Set
                Me("PR1Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR1Name() As String
            Get
                Return CType(Me("PR1Name"),String)
            End Get
            Set
                Me("PR1Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR2Profile() As String
            Get
                Return CType(Me("PR2Profile"),String)
            End Get
            Set
                Me("PR2Profile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR2Port() As String
            Get
                Return CType(Me("PR2Port"),String)
            End Get
            Set
                Me("PR2Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR2Name() As String
            Get
                Return CType(Me("PR2Name"),String)
            End Get
            Set
                Me("PR2Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR3Name() As String
            Get
                Return CType(Me("PR3Name"),String)
            End Get
            Set
                Me("PR3Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR3Port() As String
            Get
                Return CType(Me("PR3Port"),String)
            End Get
            Set
                Me("PR3Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR3Profile() As String
            Get
                Return CType(Me("PR3Profile"),String)
            End Get
            Set
                Me("PR3Profile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR4Name() As String
            Get
                Return CType(Me("PR4Name"),String)
            End Get
            Set
                Me("PR4Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR4Port() As String
            Get
                Return CType(Me("PR4Port"),String)
            End Get
            Set
                Me("PR4Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR4Profile() As String
            Get
                Return CType(Me("PR4Profile"),String)
            End Get
            Set
                Me("PR4Profile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR5Name() As String
            Get
                Return CType(Me("PR5Name"),String)
            End Get
            Set
                Me("PR5Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR5Port() As String
            Get
                Return CType(Me("PR5Port"),String)
            End Get
            Set
                Me("PR5Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR5Profile() As String
            Get
                Return CType(Me("PR5Profile"),String)
            End Get
            Set
                Me("PR5Profile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR6Name() As String
            Get
                Return CType(Me("PR6Name"),String)
            End Get
            Set
                Me("PR6Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR6Port() As String
            Get
                Return CType(Me("PR6Port"),String)
            End Get
            Set
                Me("PR6Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR6Profile() As String
            Get
                Return CType(Me("PR6Profile"),String)
            End Get
            Set
                Me("PR6Profile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR7Name() As String
            Get
                Return CType(Me("PR7Name"),String)
            End Get
            Set
                Me("PR7Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR7Port() As String
            Get
                Return CType(Me("PR7Port"),String)
            End Get
            Set
                Me("PR7Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR7Profile() As String
            Get
                Return CType(Me("PR7Profile"),String)
            End Get
            Set
                Me("PR7Profile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR8Name() As String
            Get
                Return CType(Me("PR8Name"),String)
            End Get
            Set
                Me("PR8Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR8Port() As String
            Get
                Return CType(Me("PR8Port"),String)
            End Get
            Set
                Me("PR8Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR8Profile() As String
            Get
                Return CType(Me("PR8Profile"),String)
            End Get
            Set
                Me("PR8Profile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR9Name() As String
            Get
                Return CType(Me("PR9Name"),String)
            End Get
            Set
                Me("PR9Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR9Port() As String
            Get
                Return CType(Me("PR9Port"),String)
            End Get
            Set
                Me("PR9Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR9Profile() As String
            Get
                Return CType(Me("PR9Profile"),String)
            End Get
            Set
                Me("PR9Profile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR10Name() As String
            Get
                Return CType(Me("PR10Name"),String)
            End Get
            Set
                Me("PR10Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR10Port() As String
            Get
                Return CType(Me("PR10Port"),String)
            End Get
            Set
                Me("PR10Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PR10Profile() As String
            Get
                Return CType(Me("PR10Profile"),String)
            End Get
            Set
                Me("PR10Profile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutoLink() As Boolean
            Get
                Return CType(Me("AutoLink"),Boolean)
            End Get
            Set
                Me("AutoLink") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G29")>  _
        Public Property AutoLevelCMD() As String
            Get
                Return CType(Me("AutoLevelCMD"),String)
            End Get
            Set
                Me("AutoLevelCMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.75")>  _
        Public Property FilamentDia() As String
            Get
                Return CType(Me("FilamentDia"),String)
            End Get
            Set
                Me("FilamentDia") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property Bed_ZMax() As String
            Get
                Return CType(Me("Bed_ZMax"),String)
            End Get
            Set
                Me("Bed_ZMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Heated_Build_Volume() As Boolean
            Get
                Return CType(Me("Heated_Build_Volume"),Boolean)
            End Get
            Set
                Me("Heated_Build_Volume") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CuraPath() As String
            Get
                Return CType(Me("CuraPath"),String)
            End Get
            Set
                Me("CuraPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CuraExeName() As String
            Get
                Return CType(Me("CuraExeName"),String)
            End Get
            Set
                Me("CuraExeName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CuraVersion() As String
            Get
                Return CType(Me("CuraVersion"),String)
            End Get
            Set
                Me("CuraVersion") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.EnderApp.My.MySettings
            Get
                Return Global.EnderApp.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
